# Generated by Django 4.2.2 on 2023-06-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quad_eq_solver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='root1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equation',
            name='root2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
